### ISSUE TITLE
truncated octree

### ISSUE THREAD

**Issue by arie11a0** [ladybug-tools/honeybee-dynamo#65]
Hi @mostaphaRoudsari ,
I have HoneyBee (0.1.2), Dynamo (1.3.1) and Radiance (5.0.a.12-win64)  installed on my laptop and computer.
All 3 versions are the exact version.

For some reason, my simulation fails on my computer but runs ok on my laptop.
Why is this happening? Thanks in advance.

**From laptop:**
**************
*** PID  4720: rtrace -lw 0.05 -ss 0.0 -I -h -ab 2 -ad 512 -st 0.85 -dj 0.0 -dp 64 -ds 0.5 -as 128 -dr 0 -dt 0.5 -ar 16 -aa 0.25 -e error.txt -lr 4 -dc 0.25 C:\Simulations\Daylight\gridbased\Daylight.oct

**From computer:**
**************
*** PID 13216: rtrace -lw 0.05 -ss 0.0 -I -h -ab 2 -ad 512 -st 0.85 -dj 0.0 -dp 64 -ds 0.5 -as 128 -dr 0 -dt 0.5 -ar 16 -aa 0.25 -e error.txt -lr 4 -dc 0.25 c:\Simulations\Daylight\gridbased\Daylight.oct

rtrace: fatal - (c:\Simulations\Daylight\gridbased\Daylight.oct): truncated octree

**Comment by arie11a0** [comment]
I reconnected the node in Dynamo, and ran the exact same script again.
Received the following error:

[0] ERROR:
	Handle is not initialized.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybee-plus/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "C:\Users\USER\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybeex\honeybee\radiance\recipe\gridbased.py", line 186, in writeToFile
    matFile, geoFile = self.writeHBObjectsToFile(_path, projectName)
  File "C:\Users\USER\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybeex\honeybee\radiance\recipe\_gridbasedbase.py", line 222, in writeHBObjectsToFile
    _matStr, _geoStr = self.hbObjectsToRadString()
  File "C:\Users\USER\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybeex\honeybee\radiance\recipe\_recipebase.py", line 83, in hbObjectsToRadString
    _geos.append(hbo.toRadString(includeMaterials=False, joinOutput=True))
  File "C:\Users\USER\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybeex\honeybee\hbsurface.py", line 146, in toRadString
    surfaceString = super(HBSurface, self).toRadString(includeMaterials,
  File "C:\Program Files (x86)\IronPython 2.7\Lib\abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
  File "C:\Program Files (x86)\IronPython 2.7\Lib\_weakrefset.py", line 73, in __contains__
    return wr in self.data
SystemError: Handle is not initialized.

**Comment by arie11a0** [comment]
![2017-08-14_23-00-30](https://user-images.githubusercontent.com/31008891/29277673-d9ea66d0-8144-11e7-8cf4-f72543d8bd1d.jpg)
 Picture of script running ok on my laptop

**Comment by sariths** [comment]
Hi @arie11a0 Can you share the folder where the Radiance files are being written to? Based on your error message, it should be "c:\Simulations\Daylight\gridbased\". Truncated octrees usually occur when certain rad files are missing.

**Comment by arie11a0** [comment]
[Simulations (not successful from computer).zip](https://github.com/ladybug-tools/honeybee-dynamo/files/1224541/Simulations.not.successful.from.computer.zip)
[Simulations (successful from laptop).zip](https://github.com/ladybug-tools/honeybee-dynamo/files/1224542/Simulations.successful.from.laptop.zip)

Hi @sariths , files attached. Thanks!
It is strange.. because I used to be able to run Honeybee(Dynamo) on my computer. That was only 3 months ago.

**Comment by arie11a0** [comment]
I tried completely deleting and reinstalling honeybee and radiance on my computer.

**Got the following error on the # Honeybee Surface node:**
[0] ERROR:
	Insufficient memory within specified address space range to continue the execution of the program.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybee-plus/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\uuid.py", line 557, in <module>
    NAMESPACE_DNS = UUID('6ba7b810-9dad-11d1-80b4-00c04fd430c8')
  File "C:\Program Files (x86)\IronPython 2.7\Lib\uuid.py", line 135, in __init__
    int = long(hex, 16)
MemoryError: Insufficient memory within specified address space range to continue the execution of the program.

**Got the following error on the # Run Radiance Simulation node:**
[0] ERROR:
	Item 0 is not a valid Honeybee object.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybee-plus/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 16, in <module>
AssertionError: Item 0 is not a valid Honeybee object.

![snag-0575](https://user-images.githubusercontent.com/31008891/29316236-c0d1d010-81f9-11e7-9c77-58974ab06f69.jpg)

**Comment by arie11a0** [comment]
on a side note, i am able to run Ladybug (Dynamo), although it works very slowly even for a grid of 10*10.

**Comment by sariths** [comment]
Your files are fine. This issue most likely has to do with IronPython and is happening upstream with the plugin itself. @mostaphaRoudsari will be able to answer more on this once he's back next week.

![2017-08-16 09_36_02-c__users_ssubra 1_appdata_local_temp_tmppo118lrad_scene oct](https://user-images.githubusercontent.com/10361848/29368867-87b4f934-8266-11e7-9198-708f8b0fd263.png)
![2017-08-16 09_35_35-c__users_ssubra 1_appdata_local_temp_tmpd6_qvhrad_scene oct](https://user-images.githubusercontent.com/10361848/29368866-87add5be-8266-11e7-81fa-2f40107237de.png)
![2017-08-16 09_34_03-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/10361848/29368868-87b5e36c-8266-11e7-84b9-b9fd8855c8b2.png)
![2017-08-16 09_33_13-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/10361848/29368869-87b73f32-8266-11e7-848c-78bba6b1112e.png)

**Comment by mostaphaRoudsari** [comment]
@arie11a0 thanks for posting the issue. The error `handle is not initialized` only happens in Dynamo and I have always solved the issue by re-running the node. This has to do with how Dynamo executes the graph and import the libraries.

The second issue though based on a quick search has to do with the [memory limitations](https://support.microsoft.com/en-us/help/3152158/out-of-memory-exception-in-a-managed-application-that-s-running-on-the).

Is it possible for you to install a newer version of honeybee-dynamo on your machine and give it a try? It's not yet on the package manager. Let me know if it's possible and I can share the files with you. It needs a little bit of manual work to get it installed.

**Comment by arie11a0** [comment]
Hi Mostapha,

thank you for looking into this. this is my email and you may send the files over, thank you so much!

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by arie11a0** [comment]
Hi @mostaphaRoudsari ,

how do I download and install the new files?

Cheers!

**Comment by mostaphaRoudsari** [comment]
@arie11a0 I think I will push it to the package manager by the end of the day today. That way it will be easier for you to get the new version installed.

**Comment by arie11a0** [comment]
Thanks Mostapha!

Best regards,
Adriel Sim

**Comment by mostaphaRoudsari** [comment]
Hi Adriel, Can you try the new packages and let us know if it solves the problem.

**Comment by arie11a0** [comment]
Hi @mostaphaRoudsari !

I tried one of your sample script, **04_annual_daylight_gridbased.dyn**
I got the following error at the **Annual Daylight Metrics** node.

This is the error:

>
[0] ERROR:
	Failed to load the results form an empty file: c:/Simulations\sample\gridbased_annual\result\scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/honeybee-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "C:\Users\USER\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\analysisgrid.py", line 465, in annualMetrics
    raise EmptyFileError(filePath)
EmptyFileError: Failed to load the results form an empty file: c:/Simulations\sample\gridbased_annual\result\scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.

[1] ERROR:
	Failed to load the results form an empty file: c:/Simulations\sample\gridbased_annual\result\scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/honeybee-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "C:\Users\USER\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\analysisgrid.py", line 465, in annualMetrics
    raise EmptyFileError(filePath)
EmptyFileError: Failed to load the results form an empty file: c:/Simulations\sample\gridbased_annual\result\scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.
> 

Sample file attached:
[sample.zip](https://github.com/ladybug-tools/honeybee-dynamo/files/1248919/sample.zip)

**Comment by schaggar16** [comment]
@arie11a0  did you solve the above issue? i am getting the same errors i think, started a new thread.

**Comment by mostaphaRoudsari** [comment]
This error is because the analysis doesn't run correctly. Opening a new issue helps. I will be busy today and tomorrow but will hopefully start checking the files for this issue and the similar ones starting Wednesday morning.

**Comment by mostaphaRoudsari** [comment]
@arie11a0, Thank you for sharing the folder and sorry that it took so long to check the file. The issue is that you installed Radiance under `c:\Program Files\radiance` and not `c:\radiance`. Even though we handle path with white space radiance fails to find the `cal` files under the hood. Move the radiance installation under c:\radiance and that should solve your issue. 

I also suggest to start posting your question to discourse so more people can help you with your questions: discourse.ladybug.tools

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue because of inactivity.
