### ISSUE TITLE
ERROR:  diff: 0, dir: 629, zenith: 83.741

### ISSUE THREAD

**Issue by russoluca** [ladybug-tools/honeybee-dynamo#74]
Hi everyone,

So, I've got Honeybee 0.1.5 running and whether I'm running a sample file for the annual radiation or a definition made from scratch, this error pops up from the Run Radiance Analysis node:

```
ERROR:
	diff: 0, dir: 629, zenith: 83.741

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/honeybee-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "C:\Users\Luca Russo\Documents\honeybee\radiance\recipe\radiation\gridbased.py", line 128, in write
    skycommands, skyfiles = getCommandsRadiationSky(
  File "C:\Users\Luca Russo\Documents\honeybee\radiance\recipe\recipedcutil.py", line 164, in getCommandsRadiationSky
    analemma, sunlist, analemmaMtx = \
  File "C:\Users\Luca Russo\Documents\honeybee\radiance\sky\sunmatrix.py", line 187, in execute
    solarradiance = \
  File "C:\Users\Luca Russo\Documents\honeybee\radiance\sky\gendaylit.py", line 93, in gendaylit
    skyclearness = sky_clearness(diffuseirradiance, directirradiance, sunzenith)
  File "C:\Users\Luca Russo\Documents\honeybee\radiance\sky\gendaylit.py", line 269, in sky_clearness
    raise ZeroDivisionError(msg)
ZeroDivisionError: diff: 0, dir: 629, zenith: 83.741

```
Do you have any idea about what that could mean? 
Thanks

**Comment by mostaphaRoudsari** [comment]
@russoluca which epw file are you using? This is an error inside gendaylit. I want to test it with Radiance's gendaylit first.

**Comment by mostaphaRoudsari** [comment]
This is addressed in honeybee core! https://github.com/ladybug-tools/honeybee/commit/d68b6beb9fd1d8f15f19451a4f4484f2c7b83c75
