### ISSUE TITLE
Can't find gendaymtx.exe

### ISSUE THREAD

**Issue by AlyssaHaas** [ladybug-tools/honeybee-dynamo#76]
Hi There,

I am attempting to run 05_annual_radiation_gridbased.dyn to build an understanding of how to do this type of analysis on models in dynamo and I am coming up against the error message below. I did check my app folder and I do have a file path to gendaymtx.py...

Anyhow I am a bit stuck on how to proceed and I'm not sure if its a problem with my install, I re-ran the dynamo HoneyBee installer just to make sure and still not luck. Any help would be appreciated... Now I am going to go try in Grasshopper! :)

Thank-you

C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\gendaymtx.py

--

ERROR:
	Can't find gendaymtx.exe.
Use radbinPath method to set the path to Radiance binaries before executing the command.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/honeybee-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\radiation\gridbased.py", line 128, in write
    skycommands, skyfiles = getCommandsRadiationSky(
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\recipedcutil.py", line 155, in getCommandsRadiationSky
    gdm = skymtxToGendaymtx(skyMatrix, projectFolder)
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\recipedcutil.py", line 862, in skymtxToGendaymtx
    gdm = Gendaymtx(outputName=skyMtx, weaFile=weaFilepath)
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\gendaymtx.py", line 66, in __init__
    RadianceCommand.__init__(self)
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 18, in __init__
    self.radbinPath = config.radbinPath
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 52, in radbinPath
    self.__checkExecutable(radbinPath=path, raiseException=True)
  File "C:\Users\alhaas\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 150, in _RadianceCommand__checkExecutable
    raise ValueError(__err)
ValueError: Can't find gendaymtx.exe.
Use radbinPath method to set the path to Radiance binaries before executing the command.

**Comment by mostaphaRoudsari** [comment]
@AlyssaHaas, Sorry for the late reply. As the error message says it can't find gendaymtx since it can't find Radiance installation. Where did you install Radiance? Is it installed in `c:\radiance\`? You can set it up to a different path by modifying the json file but it's not recommended.

**Comment by AlyssaHaas** [comment]
Hi Mostapha,

It was definitely a path issue. c:\radiance solves it. Thanks!
